[project]
name = "ptp-insight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
license = "GPLv3"
dependencies = [
    "fastapi[standard]==0.110.0",
    "httpx>=0.28.1",
    "influxdb>=5.3.2",
    "ruff>=0.11.7",
    "uvicorn>=0.34.2",
]
